### ISSUE TITLE
organization name

### ISSUE THREAD

**Issue by nidzieko** [Horn-Point-Labratory/moos-ivp-hpl#12]
Laboratory is spelled wrong in the organization name. I'd like to switch it from "Horn-Point-Labratory" to "horn-point-lab". You'll need to update links and such on your end for everything to work ok, so I'll let you do the switch.

**Comment by sgillen** [comment]
hah, how embarrassing. I went ahead and changed it, git is somehow smart enough to update itself, so all the repos still work. If you've linked to the page anywhere using something that's not a git repo that will need to be updated manually.
