### ISSUE TITLE
status of iAis iGpsd and pXRelayTest

### ISSUE THREAD

**Issue by sgillen** [Horn-Point-Labratory/moos-ivp-hpl#5]
I wasn't too involved with these. are they ours? and do we plan on continuing to use them/build them or should some of them be removed?

**Comment by nidzieko** [comment]
iAIS was something I hacked together from a few sources. I need to track those down. 
iGPSd is unchanged, from one of the third-part repos, and can probably go away for now. 
xrelay was just a test and can be deleted.
