### ISSUE TITLE
potential comment header 

### ISSUE THREAD

**Issue by sgillen** [Horn-Point-Labratory/moos-ivp-hpl#7]
/*===================================================================
File: [FILE NAME]
Authors: Nick Nidzieko & Sean Gillen
Date: [Date]
Origin: Horn Point Laboratory
Description: [brief description, if applicable]

 Copyright 2015 Nick Nidzieko, Sean Gillen

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

===================================================================*/

**Comment by sgillen** [comment]
Not sure exactly how to handle authorship, for example I don't think I contributed a single line to iAIS. So not sure if we should put both of us as authors of everything, try and determine who should "get" authorship of which program (which I would rather avoid) or maybe just leave it out entirely. thoughts?

**Comment by nidzieko** [comment]
I think this is good right now. If you're feeling clever, maybe consider a way to script adding the header to all files within a directory (scrubbing/modifying any existing header that you find). Maybe set a specific char sequence in the opening (and closing?) lines of the comment block. eg:
/_===GNU-GPL==== 
etc
etc
=======_/
