### ISSUE TITLE
splitting up uSimROMS

### ISSUE THREAD

**Issue by sgillen** [Horn-Point-Labratory/moos-ivp-hpl#8]
it seems like checking bathymetry for safety and  simulating salinity etc. data should be seperate processes?

**Comment by nidzieko** [comment]
agreed.

**Comment by nidzieko** [comment]
Seems like the right way to do this might be to transition the ROMS read to a library function and then have processes (or behaviors?) that utilize that information. Publishing salinity and velocity fields might be a process while (potentially) avoiding upcoming bathymetric changes might be best as a behavior?
